name: frd
channels:
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - libcxx=12.0.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libopenblas=0.3.20
  - llvm-openmp=12.0.0
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pip=21.2.4
  - pyparsing=3.0.4
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2022.1
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
